version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.8.0-alpha.2
    environment:
      - DSN=postgres://kratos:secret@host.docker.internal:5432/kaldstart-ory-kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - kaldstart-intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.8.0-alpha.2
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@host.docker.internal:5432/kaldstart-ory-kratos?sslmode=disable&max_conns=20&max_idle_conns=4
#      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos/email-password
        target: /etc/config/kratos
    networks:
      - kaldstart-intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - kaldstart-intranet

networks:
  kaldstart-intranet:
